// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Datatable from './datatable_controller'
application.register('datatable', Datatable)

import Clipboard from './clipboard_controller'
application.register('clipboard', Clipboard)

import Menu from './menu_controller'
application.register('menu', Menu)

import TransactionForm from './transaction_form_controller'
application.register('transaction-form', TransactionForm)

import Select from './select_controller'
application.register('select', Select)
