development:
  secret_key_base: f196861eed46b817be7402ec85f917fa19c7a2f7a4f17e1ee4c9e8f657eea809be7a56951bd0af1f339237d1bcef739f4f5206ba06d68bcbe24866a8cb1e6b5f
  omniauth_client_id: tomtest
  omniauth_client_secret: blargh
  sidekiq_username: dhh
  sidekiq_password: jobs

test:
  secret_key_base: 74b63cafd732dfbdddede69122e2735485c9b30392b068d6260495fafd3c2cd71209fc396acdd3f06ab27f63b605fd31f9e76a5e4d5d3426878cb27dccba4db1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  omniauth_client_id: <%= ENV["OMNIAUTH_CLIENT_ID"] %>
  omniauth_client_secret: <%= ENV["OMNIAUTH_CLIENT_SECRET"] %>
  sidekiq_username: <%= ENV["SIDEKIQ_USERNAME"] %>
  sidekiq_password: <%= ENV["SIDEKIQ_PASSWORD"] %>
